gem.json
repo.json

repo files

---

Code/Source/Sensor/ROS2SensorComponent.cpp
Code/Source/Sensor/SensorConfiguration.h

Publishing toggle

---

Code/CMakeLists.txt
Code/Include/ROS2/ROS2Bus.h
Code/Source/Frame/NamespaceConfiguration.cpp
Code/Source/Frame/NamespaceConfiguration.h
Code/Source/Frame/ROS2FrameComponent.cpp
Code/Source/Frame/ROS2FrameComponent.h
Code/Source/Frame/ROS2Transform.cpp
Code/Source/Frame/ROS2Transform.h
Code/Source/ROS2ModuleInterface.h
Code/Source/ROS2SystemComponent.cpp
Code/Source/ROS2SystemComponent.h
Code/Source/Utilities/ROS2Conversions.cpp
Code/Source/Utilities/ROS2Conversions.h
Code/Source/Utilities/ROS2Names.cpp
Code/Source/Utilities/ROS2Names.h
Code/ros2_files.cmake

- Static frames publishing (e.g. for fixed joints, many sensors)
- Dynamic frame publishing (to global frame) - Fixes #12
- Handling of namespaces - Fixes #10
- Several utilities for ROS2 conversions and names needed for frames/transforms

ROS2Frame component:

---

Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Code/Source/Lidar/ROS2LidarSensorComponent.h
Code/Source/Sensor/PublisherConfiguration.cpp
Code/Source/Sensor/PublisherConfiguration.h
Code/Source/Sensor/ROS2SensorComponent.cpp
Code/Source/Sensor/ROS2SensorComponent.h
Code/Source/Sensor/SensorConfiguration.cpp
Code/Source/Sensor/SensorConfiguration.h
Code/Source/Utilities/ROS2Names.cpp
Code/ros2_files.cmake

Supporting multiple publisher

---

Code/Source/RobotControl/ROS2RobotControlComponent.cpp
Code/Source/RobotControl/ROS2RobotControlComponent.h

Develops https://github.com/RobotecAI/o3de-ros2-gem/issues/25

Robot control namespace

---

Code/Source/Clock/SimulationClock.cpp
Code/Source/Frame/ROS2Transform.h
Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Code/Source/QoS/QoS.cpp
Code/Source/QoS/QoS.h
Code/Source/RobotControl/ROS2RobotControlComponent.cpp
Code/Source/RobotControl/ROS2RobotControlComponent.h
Code/Source/RobotControl/RobotControl.h
Code/Source/Sensor/PublisherConfiguration.cpp
Code/Source/Sensor/PublisherConfiguration.h
Code/Source/Sensor/ROS2SensorComponent.cpp
Code/ros2_files.cmake

QoS class and usage in sensor publishers and robot control

---

Code/Source/Frame/ROS2Transform.cpp

Transform fix

---

Code/Source/Lidar/LidarTemplate.cpp
Code/Source/Lidar/LidarTemplate.h
Code/Source/Lidar/LidarTemplateUtils.cpp
Code/Source/Lidar/LidarTemplateUtils.h
Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Code/Source/Lidar/ROS2LidarSensorComponent.h
Code/ros2_files.cmake

a bit of refactor of lidar template

---

Code/Include/ROS2/ROS2Bus.h
Code/Source/Frame/ROS2Transform.cpp
Code/Source/Frame/ROS2Transform.h
Code/Source/ROS2SystemComponent.cpp
Code/Source/ROS2SystemComponent.h

Transform broadcasters need to be one per node

---

Code/Source/Lidar/LidarTemplateUtils.cpp
Code/Source/Lidar/LidarTemplateUtils.h
Code/Source/Lidar/ROS2LidarSensorComponent.cpp

Fixed:
- lidar beam directions
- results in local frame

Fixed lidar orientation and points frame

---

Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Code/Source/Sensor/PublisherConfiguration.h
Code/Source/Sensor/ROS2SensorComponent.cpp
Code/Source/Sensor/ROS2SensorComponent.h
Code/Source/Sensor/SensorConfiguration.h

Switched map entries from pointers to by value due to serialization crash

---

Code/Source/RobotControl/ROS2RobotControlComponent.cpp

Fix #45 reflection for QoS

---

Code/Source/ROS2SystemComponent.cpp
Code/Source/Sensor/PublisherConfiguration.cpp
Code/Source/Sensor/SensorConfiguration.cpp

Reflection of common structs moved to system component

---

Code/Include/ROS2/ROS2Bus.h
Code/Source/Frame/ROS2Transform.cpp
Code/Source/Frame/ROS2Transform.h
Code/Source/ROS2SystemComponent.cpp
Code/Source/ROS2SystemComponent.h

Fixes #37
Transforms now work correctly with rviz2. 

Dynamic transform fix

---

Code/Source/Imu/ROS2ImuSensorComponent.cpp
Code/Source/Imu/ROS2ImuSensorComponent.h
Code/Source/ROS2ModuleInterface.h
Code/ros2_files.cmake

IMU sensor, first version.
Signed-off-by: Michal Drwiega <michal.drwiega@robotec.ai>

IMU sensor

---

Code/Include/ROS2/ROS2Bus.h

Documentation of ROS2Requests (ROS2Interface)

---

Code/Source/Clock/SimulationClock.cpp
Code/Source/Clock/SimulationClock.h
Code/Source/Frame/NamespaceConfiguration.h
Code/Source/Frame/ROS2FrameComponent.cpp
Code/Source/Frame/ROS2FrameComponent.h
Code/Source/Frame/ROS2Transform.h
Code/Source/Imu/ROS2ImuSensorComponent.cpp
Code/Source/Imu/ROS2ImuSensorComponent.h
Code/Source/Lidar/LidarRaycaster.cpp
Code/Source/Lidar/LidarRaycaster.h
Code/Source/Lidar/LidarTemplate.h
Code/Source/Lidar/LidarTemplateUtils.h
Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Code/Source/Lidar/ROS2LidarSensorComponent.h
Code/Source/QoS/QoS.h
Code/Source/Sensor/PublisherConfiguration.h
Code/Source/Sensor/ROS2SensorComponent.cpp
Code/Source/Sensor/ROS2SensorComponent.h
Code/Source/Sensor/SensorConfiguration.h

Documentation + header cleanup.
- Documentation for Sensor, Lidar, IMU, Frame and QoS
- Header cleanup: ordering and removing unnecesary ones

Documentation doxy (#69) - pt. 1

---

README.md

Readme instructions for the Gem

---

README.md

* Readme instructions for the Gem

Readme instructions for the Gem (#79)

---

Assets/Prefabs/Sensors/Imu.prefab

Changed structure, added ROS2 sensor

Imu prefab refactor

---

Assets/Prefabs/Sensors/LidarOS2.prefab
Code/Source/Lidar/LidarRaycaster.cpp
Code/Source/Lidar/LidarRaycaster.h
Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Code/Source/Lidar/ROS2LidarSensorComponent.h
Code/Source/RobotControl/RobotControl.h

Signed-off-by: Piotr Jaroszek <piotr.jaroszek@robotec.ai>

Lidar self collision filter, updated prefab

---

Code/Source/Sensor/ROS2SensorComponent.cpp
Code/Source/Sensor/ROS2SensorComponent.h

fix - removed prototype static and replaced with a member

---

Code/Source/Lidar/LidarTemplate.cpp
Code/Source/Lidar/LidarTemplate.h
Code/Source/Lidar/LidarTemplateUtils.cpp
Code/Source/Lidar/LidarTemplateUtils.h
Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Code/Source/Lidar/ROS2LidarSensorComponent.h

Generic lidar is now configurable in Editor

---

Assets/Prefabs/Sensors/Imu.prefab

A better IMU prefab
- names
- actually has a sensor

Imu prefab refactor (#85)
